numbers = list(map(int, input().split()))
min_of_numbers = min(numbers)
max_of_numbers = max(numbers)
sum_of_numbers = sum(numbers)
print(f"The minimum number is {min_of_numbers}")
print(f"The maximum number is {max_of_numbers}")
print(f"The sum number is: {sum_of_numbers}")